import { Schema } from "mongoose";

export interface IOpenAIGenerationResult {
    /**
     * The response generated by the OpenAI API
     */
    readonly aiResponse: string;
    /**
     * The ID of the post in mongo
     */
    readonly postId?: Schema.Types.ObjectId;
}

/**
 * The result of a call to the OpenAI API for the initial words and prompt.
 */
export class OpenAIGenerationResult implements IOpenAIGenerationResult {
    /**
     * The response generated by the OpenAI API
     */
    readonly aiResponse: string;
    /**
     * The ID of the post in mongo
     */
    readonly postId?: Schema.Types.ObjectId;
    constructor(other: IOpenAIGenerationResult) {
        this.aiResponse = other.aiResponse;
        this.postId = other.postId;
    }
}
